version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Preparing build...

  build:
    commands:
      - echo Building application...
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Starting application...
      - node server.js
artifacts:
  files:
    - '**/*'
  discard-paths: no