version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install
      - sudo yum install -y jq  # Install jq for JSON parsing

  pre_build:
    commands:
      - echo "Fetching secrets from AWS Secrets Manager..."
      - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id credential-login --region ap-southeast-1 --query SecretString --output text || exit 1)
      - echo "Creating .env file..."
      - echo "$SECRET_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .env

  build:
    commands:
      - echo "Building application..."
      - echo "Build completed on $(date)"

  post_build:
    commands:
      - echo "Starting application..."

artifacts:
  files:
    - '**/*'
  discard-paths: false