version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo "Fetching secrets from Secrets Manager..."
      - |
        SECRET_JSON=$(aws secretsmanager get-secret-value \
          --secret-id credential-login \
          --region ap-southeast-1 \
          --query SecretString \
          --output text)
      - echo "Creating .env file..."
      - |
        echo "$SECRET_JSON" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > .env
      - echo "Created .env with keys: $(cat .env | cut -d= -f1)"
  build:
    commands:
      - echo Building application...
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Starting application...
artifacts:
  files:
    - '**/*'
  discard-paths: no